"""add_perspectives_jsonb

Revision ID: 274aa5d3654e
Revises: 0005
Create Date: 2026-08-29 07:13:22.995649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '274aa5d3654e'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('perspectives', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    
    # Data migration: Copy existing columns to perspectives JSONB
    op.execute(
        "UPDATE inquiries SET perspectives = jsonb_build_object("
        "  'buddhism', buddhism,"
        "  'western_philosophy', western_philosophy,"
        "  'psychology', psychology"
        ")"
    )
    
    op.alter_column('inquiries', 'buddhism',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('inquiries', 'western_philosophy',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('inquiries', 'psychology',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore columns from JSONB data before making them non-nullable
    op.execute(
        "UPDATE inquiries SET "
        "  buddhism = COALESCE(perspectives->>'buddhism', ''),"
        "  western_philosophy = COALESCE(perspectives->>'western_philosophy', ''),"
        "  psychology = COALESCE(perspectives->>'psychology', '')"
    )
    
    op.alter_column('inquiries', 'psychology',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('inquiries', 'western_philosophy',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('inquiries', 'buddhism',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('inquiries', 'perspectives')
    # ### end Alembic commands ###
